package com.jboss.examples.drools.cep.alerts.model;

import java.util.Date;

/**
 * An initial alert generated by the system.
 * 
 * @author Jeremy Davis jeremy.davis@redhat.com
 *
 */
public class InitialAlert {

	protected String id;

	protected Date time;

	protected String deviceName;

	protected String interfaceName;

	protected AlertStatus status;

	public InitialAlert(String idToSet, Date timeToSet, String deviceNameToSet,
			String interfaceNameToSet, AlertStatus active) {
		// TODO Auto-generated constructor stub
	}

	//--------------------------------------------------------------------------
	//	generated getters and setters
	//--------------------------------------------------------------------------
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getDeviceName() {
		return deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	public String getInterfaceName() {
		return interfaceName;
	}

	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}

	public AlertStatus getStatus() {
		return status;
	}

	public void setStatus(AlertStatus status) {
		this.status = status;
	}
	
}
